# Generated by Django 4.0.4 on 2022-10-18 01:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("Blog", "0002_alter_autor_options_alter_seccion_options"),
    ]

    operations = [
        migrations.CreateModel(
            name="Avatar",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "imagen",
                    models.ImageField(blank=True, null=True, upload_to="avatares"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Avatar",
                "verbose_name_plural": "Avatares",
            },
        ),
        migrations.CreateModel(
            name="Comentario",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("autor", models.CharField(max_length=40)),
                ("email", models.EmailField(max_length=254)),
                ("cuerpo", models.TextField(verbose_name="")),
                ("fecha", models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="Posteo",
            fields=[
                ("autor", models.CharField(max_length=40)),
                ("email", models.EmailField(max_length=254)),
                ("fecha", models.DateField(auto_now_add=True)),
                (
                    "titulo",
                    models.CharField(max_length=40, primary_key=True, serialize=False),
                ),
                ("cuerpo", models.TextField(verbose_name="")),
            ],
        ),
        migrations.CreateModel(
            name="Usuario",
            fields=[
                ("nombre", models.CharField(max_length=40)),
                ("apellido", models.CharField(max_length=40)),
                ("dni", models.IntegerField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.DeleteModel(
            name="Articulo",
        ),
        migrations.DeleteModel(
            name="Autor",
        ),
        migrations.DeleteModel(
            name="Seccion",
        ),
    ]
