# Generated by Django 4.0.4 on 2022-10-20 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Blog", "0003_avatar_comentario_posteo_usuario_delete_articulo_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="posteo",
            name="imagen",
            field=models.ImageField(blank=True, null=True, upload_to="avatares"),
        ),
    ]
