# Generated by Django 4.0.4 on 2022-10-21 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Blog", "0005_alter_posteo_imagen"),
    ]

    operations = [
        migrations.AlterField(
            model_name="posteo",
            name="imagen",
            field=models.ImageField(blank=True, null=True, upload_to="avatares"),
        ),
    ]
