# Generated by Django 4.0.4 on 2022-10-21 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Blog", "0006_alter_posteo_imagen"),
    ]

    operations = [
        migrations.CreateModel(
            name="Perfil",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.EmailField(max_length=254)),
                ("first_name", models.CharField(max_length=50)),
                ("last_name", models.CharField(max_length=50)),
                ("descripcion", models.TextField(verbose_name="")),
                ("link", models.CharField(max_length=50)),
            ],
        ),
    ]
