# Generated by Django 4.0.4 on 2022-10-21 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Blog", "0008_delete_perfil"),
    ]

    operations = [
        migrations.CreateModel(
            name="Perfil",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=40)),
                ("last_name", models.CharField(max_length=40)),
                ("email", models.EmailField(max_length=40)),
                ("link", models.CharField(max_length=40)),
                ("descripcion", models.CharField(max_length=200)),
            ],
        ),
    ]
