# Generated by Django 4.0.4 on 2022-10-21 05:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Blog", "0009_perfil"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Perfil",
        ),
    ]
