# Generated by Django 4.0.4 on 2022-10-22 00:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Blog", "0011_perfil"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="perfil",
            name="descripcion",
        ),
        migrations.RemoveField(
            model_name="perfil",
            name="link",
        ),
    ]
